### ISSUE TITLE
Convert Contactless Support Interest Google form to HTML form

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/mobility-marketplace#332]
## Background

On the [Contact page](https://www.camobilitymarketplace.org/contact), we embed an HTML form that submits to Netlify using their form system (a few attributes on the `<form>` tag).

We have a Zapier task set up to watch for submissions of this Netlify form, and forward these to Teamwork Desk as a ticket to the `hello@calitp.org` inbox.

We should have a similar workflow for the [*Contactless Payments on Public Transportation: Interest Form for Cal-ITP Support*](https://docs.google.com/forms/d/e/1FAIpQLSfc4UungS-RkMfukZubgn8cZel8aLbfDS_y-UfyxD1Jkx34NQ/viewform) referenced from the Resources page and currently implemented as a Google form.

## Tasks

This issue tracks just the form conversion; #334 tracks the Desk submission

* [x] Create a new `.html` page with the intro text content from the Google form
* [x] Recreate the Google form as a regular HTML form, including required fields and field notes
* [x] Wire the HTML form to Netlify
