### ISSUE TITLE
Configure repo with devcontainer

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/mobility-marketplace#335]
## Background

This repo has a [`docker-compose.yml`](https://github.com/cal-itp/mobility-marketplace/blob/main/docker-compose.yml) file that makes  development and running locally fairly straightforward.

But we are trying to standardize on devcontainers with pre-commit and other tooling to streamline the dev experience and ease future onboarding.

## Tasks

* [x] `mkdir .devcontainer`
* [x] `mv docker-compose.yml .devcontainer/compose.yml`
* [x] `touch .devcontainer/devcontainer.json` - see the [Benefits `devcontainer.json`](https://github.com/cal-itp/benefits/blob/dev/.devcontainer/devcontainer.json) as an example
* [x] Rework Docker to install both jekyll (ruby) and pre-commit (python)
* [x] `touch .pre-commit-config.yaml` - see the [Benefits `.pre-commit-config.yaml`](https://github.com/cal-itp/benefits/blob/dev/.pre-commit-config.yaml) as an example
* [x] Configure a `postAttach.sh` script to setup pre-commit in the devcontainer
* [x] Update README with new steps to get started
