### ISSUE TITLE
Clean up unused content/config

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/mobility-marketplace#336]
While minor, this stuff adds unnecessary build steps/time and is just clutter. As part of #335, we want a clean environment.

## Tasks

* [x] Delete directory `_articles/` (unused collection)
* [x] Delete `_layouts/articles.html` (unused collection)
* [x] Delete directory `_posts/` (unused collection)
* [x] Delete directory `admin/` (unused CMS config)
* [x] Delete directory `docs/` (HTML5 boilerplate docs)
* [x] Delete `CONDUCT.md` (need something for Cal-ITP)
* [x] Delete `humans.txt` (unmaintained)
* [x] Delete `robots.txt` (unnecessary)
* [x] In `_config.yml`:
  * [x] Delete [`authors`](https://github.com/cal-itp/mobility-marketplace/blob/main/_config.yml#L32) (unmaintained)
  * [x] Delete [`collections.articles`](https://github.com/cal-itp/mobility-marketplace/blob/main/_config.yml#L43) (unused)
  * [x] Clean up [`exclude`](https://github.com/cal-itp/mobility-marketplace/blob/main/_config.yml#L84) with the renames and deletions
