### ISSUE TITLE
[TRACKING] Implement new For Vendors page

### ISSUE THREAD

**Issue by mrose914** [cal-itp/mobility-marketplace#442]
See wireframes here: https://www.figma.com/file/TfWk1iDHdlt7bSA3DjQuQv/Mobility-Marketplace?type=design&node-id=6921-1040&mode=design&t=R40wIO4T8qpljlNA-0

And tickets here: 

- [x] https://github.com/cal-itp/mobility-marketplace/issues/500
- [x] https://github.com/cal-itp/mobility-marketplace/issues/499
- [x] https://github.com/cal-itp/mobility-marketplace/issues/498
- [x] https://github.com/cal-itp/mobility-marketplace/issues/497
- [x] https://github.com/cal-itp/mobility-marketplace/issues/496
- [x] https://github.com/cal-itp/mobility-marketplace/issues/495

**Comment by thekaveman** [comment]
Removing assignment until we are unblocked -- we have a few items going this sprint so not sure who will take this one.

**Comment by vykster** [comment]
@mrose914 what are the blockers left here?

Also following up from APTA tech, can we create a interest form? We have a lot of vendors asking to get info when a new RFP, MSA, or market sounding is released. MVP seems to be vendor name, contact info (name, email), and vendor type. 


cc / @o-ram if we have a signup form for notifications we'd also need an internal email list/ plan to send out a notification when they get posted.

**Comment by vykster** [comment]
great. I can use this in the short term.

**Comment by machikoyasuda** [comment]
Dev needs:
- All copy content approved
- All images/illustrations as SVGs, including for the statistic area
